function add_figure_title(fig_title)
    if exist('sgtitle', 'builtin') == 5
        sgtitle(fig_title, 'FontSize', 12, 'FontWeight', 'bold');
    else
        annotation('textbox', [0, 0.95, 1, 0.05], ...
            'String', fig_title, ...
            'EdgeColor', 'none', ...
            'HorizontalAlignment', 'center', ...
            'VerticalAlignment', 'top', ...
            'FontSize', 12, ...
            'FontWeight', 'bold');
    end
end
